name: FreeThinkers
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  eva_icons_flutter: ^2.0.0
  outline_material_icons: ^0.1.1
  carousel_slider: ^2.0.0
  url_launcher: ^5.4.7
  uuid: ^2.0.4
  fluttertoast: ^4.0.1
  provider: ^4.1.2
  string_validator: ^0.1.4
  cached_network_image: ^2.2.0+1
  badges: ^1.1.1
  firebase_core: ^0.5.0
  firebase_database: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/telekom.png
